const json = {
  "1": "Sensor01Tof",
  "2": "Sensor01PtP",
  "3": "Sensor02Tof",
  "4": "Sensor02PtP",
  "5": "Sensor03Tof",
  "6": "Sensor03PtP",
  "7": "Sensor04Tof",
  "8": "Sensor04PtP",
  "9": "Sensor05Tof",
  "10": "Sensor05PtP",
  "11": "ConcentricityOffset",
  "12": "ProfileOffset",
  "13": "ANYFAULT",
  "14": "SampleTime",
  "15": "StatusWord",
  "16": "EulerAngles_Roll",
  "17": "EulerAngles_Pitch",
  "18": "EulerAngles_Yaw",
  "19": "DeltaV_X",
  "20": "DeltaV_Y",
  "21": "DeltaV_Z",
  "22": "RateOfTurn_gyrX",
  "23": "RateOfTurn_gyrY",
  "24": "RateOfTurn_gyrZ",
  "25": "Acceleration_accX",
  "26": "Acceleration_accY",
  "27": "Acceleration_accZ",
  "28": "MagneticField_magX",
  "29": "MagneticField_magY",
  "30": "MagneticField_magZ",
  "31": "Error"
};
export default json;
